language: "node_js"
node_js:
  - "12"
  - "11"
  - "10"

before script:
  #- "npm install athena-express"

before_install:
  - "npm install"

script: 
  - npm start

after_script:
  - npm run coveralls